name: .NET 8 CI Build and Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
          
      - name: List directory contents
        run: ls -la

      - name: Restore dependencies
        run: dotnet restore        
        working-directory: RentAWreckApi

      - name: Build the solution
        run: dotnet build --no-restore
        working-directory: RentAWreckApi

      - name: Run unit tests
        run: dotnet test --no-build UnitTests/UnitTests.csproj
        working-directory: RentAWreckApi

      - name: Run integration tests
        run: dotnet test --no-build IntegrationTests/IntegrationTests.csproj
        working-directory: RentAWreckApi
